### ISSUE TITLE
Current fix to Pyro 3 issue "knee caps" passing on python code to be executed

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#106]
In commit bddb03efb2f34e122f6cfd5d, the communication between the server and the executors was changed due to changes in the behavior of Pyro 3 / Python 2.7. Originally the stage to be processed was passed on as an object. Then, it was run by invoking stage.execStage(). When we updated to Ubuntu Precise, it was not possible anymore to pass objects using Pyro 3. As a result, instead of passing on the object, the command to be run is now passed on to the pipeline executor as a string, and executed using subprocess.Popen. This disables the possibility to run a stage which is given by some python code (not a command line program). This should be reinstated. Pyro 3 is not supported anymore, so we need to move on to Pyro 4. Check also that shutting down the executors using pids (process IDs) is still a valid way in the case where we have stages that are not command line programs, but pieces of python code.

**Comment by bcdarwin** [comment]
In the current incarnation most stages still consist primarily of shell commands to be run, although we also have several "hooks" which allow attaching arbitrary Python code and which may run on the server or executor side.  We don't have a canonical way of running a command as pure Python but you could certainly use hooks to simulate this; we could add such a mechanism if desired.  On the other hand, we currently determine stage dependencies from input and output files, which is problematic for some applications of this idea.  Also, encoding more logic inside the program would make (say) adapting a different backend execution engine more difficult.
