### ISSUE TITLE
--lsq6-target for MBM.py is broken

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#109]
There are too many places where the code assumes there is an an initial model around. For instance, you'll have to use --lsq12-likefile in combination with --lsq6-target. And even when you do that, you'll strand here:

https://github.com/mfriedel/pydpiper/blob/master/applications/MBM.py#L87

**Comment by jasonlerch** [comment]
Been fixed.
