### ISSUE TITLE
Server shoule be able to launch executors with different amounts of memory

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#111]
When a full MBM pipeline is run, most stages require only 2G of memory. A couple however, require 6G. A way to deal with this is to have your server launch 6G executors only which is very resource inefficient. Another is to run your pipeline with 2G jobs, until it stalls, and then resubmit with executors with more memory. Both are not very good solutions. So the server should be able to launch the kinds of executors it needs

**Comment by bcdarwin** [comment]
Crude implementation (all executors launched will request memory equal to the largest amount required by any queued job) in 8b76ba59a9.

**Comment by bcdarwin** [comment]
Reopen if encountering a situation where the current system grossly overestimates memory requirements.
