### ISSUE TITLE
Guidelines for PBS/SGE executors?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#140]
How does one decide how many executors to spawn for SGE/PBS?

For a local machine it makes sense to spawn as many as there are local CPUs, but how does one decide for a batch system?

**Comment by bcdarwin** [comment]
There's some current documentation on this under 'running a job' at https://wiki.mouseimaging.ca/display/MICePub/Running+Pydpiper+on+SciNet

**Comment by bcdarwin** [comment]
Possibly this documentation should be in a more obvious place than the Pydpiper-on-SciNet HOWTO.

**Comment by gdevenyi** [comment]
Resolved
