### ISSUE TITLE
Verify that we can control the use of /tmp

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#141]
Henrik Westerberg mentioned that MBM.py was using /tmp and wanted to know whether there is a way to get around that. I know that rotational_minctracc.py potentially uses /tmp, but that can be controlled using the environment variable TMPDIR. We should check that something like this works for the entire pipeline.

**Comment by jasonlerch** [comment]
Likely an issue in the minc tools that we use, not in pydpiper.

**Comment by vfonov** [comment]
most minc script rely on TMPDIR environment variable for location where to store temporary files.
