### ISSUE TITLE
1.11 release soon?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#163]
How's 1.11-alpha doing?

I'm about start a big batch of processing, wondering if I should upgrade to 1.11-alpha or perhaps to HEAD?

Or will there be a release soon?

**Comment by mcvaneede** [comment]
We're very actively working on a new release. After some final tests we hope to have the release done later tomorrow.

**Comment by gdevenyi** [comment]
Awesome, cheers!

**Comment by bcdarwin** [comment]
Due to breakage in the registration_chain and MAGeT applications caused by recent changes, we won't be able to make a release before the weekend.  Apart from those fixes, the current develop branch should be very similar to the released version.

**Comment by mcvaneede** [comment]
It's there Gabriel!

**Comment by gdevenyi** [comment]
Hurrah! Thanks!

-- 
Gabriel A. Devenyi B.Eng. Ph.D.
Research Computing Associate
Computational Brain Anatomy Laboratory
Cerebral Imaging Center
Douglas Mental Health University Institute
McGill University
t: 514.761.6131x4781
e: gdevenyi@gmail.com

On Tue, Jan 13, 2015 at 5:42 PM, Matthijs van Eede <notifications@github.com
