### ISSUE TITLE
--lsq6-target does not work (for me)

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/pydpiper#166]
If you try to run a lsq6 pipeline without an initial model (no --init-model) but with --lsq6-target the pipeline dies since the variable InitModel is left set as None
See registration_functions.py function setInitialTarget

Error thrown is:
Error: resampleINORMtoLSQ6Space does not know what to do without an initial model at this moment. Sorry. Goodbye.

**Comment by mcvaneede** [comment]
This is fixed in the latest release (v1.11). Can you give it a try?

**Comment by psteadman** [comment]
Yes looks good no error is produced, haven't check if output is proper yet but looks fine.
