### ISSUE TITLE
Two lsq6 operations performed in one pipeline

### ISSUE THREAD

**Issue by kbeera** [Mouse-Imaging-Centre/pydpiper#170]
A pipeline I ran recently on CT data resulted in a lsq6 registration before *and* after intensity normalization. Here was the command used:

MBM.py --pipeline-name=OB_position_analysis_jan102015 --no-nuc --init-model=/projects/souris/kbeera/focal_irradiations/OB/position_analysis/init_model/OB_mou11_preTRT_cropped.mnc --lsq6-simple --lsq6-protocol=minctracc_linear_protocol.csv --lsq12-protocol=minctracc_linear_protocol.csv --nlin-protocol=minctracc_nlin_protocol_200u.csv --registration-method=minctracc --calc-stats OB_mou1_preTRT_cropped.mnc OB_mou2_preTRT_cropped.mnc OB_mou3_preTRT_cropped.mnc OB_mou4_preTRT_cropped.mnc OB_mou9_preTRT_cropped.mnc OB_mou10_preTRT_cropped.mnc OB_mou11_preTRT_cropped.mnc OB_mou12_preTRT_cropped.mnc OB_mou13_preTRT_cropped.mnc OB_mou14_preTRT_cropped.mnc OB_mou15_preTRT_cropped.mnc  --num-executors=4 --proc=2 --mem=2

My guess is that a combination of providing a lsq6 protocol and specifying --lsq6-simple is causing the issue.

**Comment by mcvaneede** [comment]
In general we try to reduce the number of resamplings a file goes through during a registration pipeline. The idea is that each stage (lsq6, lsq12, nlin) start from a file that directly comes from the native space. For this reason when a file undergoes intensity normalization (or non uniformity correction), this is initially performed in native space. Then, it's resampled to the lsq6 space. So there will always be an _inorm.mnc (in native space) and an _inorm_lsq6.mnc file (simply resampled to that space). So only one lsq6 registration was performed in your pipeline.

**Comment by mcvaneede** [comment]
So the issue is that the intensity normalization is not being done in native space, but in lsq6 space. The code thinks that it still needs to be resampled to lsq6 space, at which point the lsq6 transformation is applied twice.
