### ISSUE TITLE
MAGeT.py how to set pairwise?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#174]
``--no-pairwise`` is the default on the command line and it appears that there is no way turn it off.

``--no-pairwise false`` does seem to work

**Comment by bcdarwin** [comment]
In fact the default is pairwise, but the help message for `--no-pairwise` was wrong.  I've added an explicit `--pairwise` flag and clarified the defaults in the help strings on the `develop` branch.

**Comment by gdevenyi** [comment]
Fixed by 2c0da07ac36646043b100fe1911963673a4c9986
