### ISSUE TITLE
clean /dev/shm before executor exits

### ISSUE THREAD

**Issue by jasonlerch** [Mouse-Imaging-Centre/pydpiper#180]

**Comment by bcdarwin** [comment]
With this patch, the executor just does a rm * on /dev/shm, which works for the SciNet configuration but wouldn't work on our local cluster (it might erase files in use by another executor on the same node).  Perhaps the easiest thing to do is add some sort of cleanup action to each stage which uses /dev/shm -- this could be done already by constructing cmdstages with multi-phrase/line commands, but this will clutter the graph/logfiles with details about cleanup.

**Comment by gdevenyi** [comment]
What about using https://docs.python.org/2/library/tempfile.html to create a temporary dir within /dev/shm so that you exactly know the directory to remove?

**Comment by bcdarwin** [comment]
closing for now since rotational_minctracc.py no longer wastes lots of /dev/shm space
