### ISSUE TITLE
Reduce the number of resamplings to a minimum

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#184]
At each new stage in the pipeline (lsq6, lsq12, nlin), the input file to that stage should only have been resampled once. For instance the input to nlin, should come from a single resample command where the lsq6 and lsq12 transformations have been concatenated, and the native input file is resampled with that concatenated transform.

**Comment by bcdarwin** [comment]
This should now be the case; open a new issue if you find a counterexample.
