### ISSUE TITLE
pydpiper pbs jobfiles stored outside run directory

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#193]
I expected to find jobfiles for the pbs executors in my running directory for MAGeT.py, but instead I find that a directory ~/pbs-jobs was created and the jobfiles are there.

While the naming looks like it will prevent collisions, it would be better to store those files in the running directory of MAGeT.py

**Comment by bcdarwin** [comment]
Fixed on develop branch.
