### ISSUE TITLE
Memory specification of pbs-jobs

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/pydpiper#194]
I know with sge clusters and the sge_batch script you have the --mem option to specify the amount of memory requested. I would like this extended to when --queue-type pbs is specified to request a specific amount of memory for the pbs-jobs.
Thanks :)
It shouldn't be a hard fix, just change in queueing.py the function addHeaderAndCommands line 136

``` sh
self.jobFile.write("#PBS -l nodes=%d:ppn=%d,walltime=%s\n" % (requestNodes, self.ppn, timestr))
TO
self.jobFile.write("#PBS -l nodes=%d:ppn=%d,mem=%dgb,walltime=%s\n" % (requestNodes, self.ppn, self.mem, timestr))
```

My solution may not be correct...

**Comment by psteadman** [comment]
Okay its a bit more complicated than this, but this is maybe something to think about. Basically I use pydpiper on the Sickkid's cluster and they only want you to control the vmem option (as opposed to the mem and pmem) so a solution as I proposed above only changes mem, which doesn't work on the HSC cluster but if I change it to vmem it does work. This suggests its really going to be specific to the queue set-up unfortunately... I leave this to you, I can always edit pydpiper code to suite my specific needs.
Cheers,
Patrick

**Comment by mcvaneede** [comment]
I currently can't access SickKids's website detailing job submissions on their cluster. But I gather that the way they want you to request memory would then be:

vmem=...gb

As you said, a quick solution for you at the moment is to add those changes into your code, but we'll incorporate it in one of the future releases as well.

**Comment by psteadman** [comment]
Yes exactly. They have a wiki but its not detailed like scinet. They allow
memory requests under the vmem option only. I will make the change in my
version, but something for you all to think about going forward. mem, vmem
and pmem... so delightful!

**Comment by bcdarwin** [comment]
We could create an option similar to qsub's '-l' which allows you to pass a string of form <memtype>=<amt> which would be passed on in the appropriate way depending on the queue type (assuming there's only one sensible way to do this on SGE and one on PBS).

**Comment by bcdarwin** [comment]
So the recommended way to set this on HPF (undocumented?, but according to Fernando) is now to request both vmem and mem, which can be done in Pydpiper via --mem-request-attribute=vmem,mem (should be 'attributes' now ...)
