### ISSUE TITLE
pydpiper on SciNet - resurrecting lost jobs

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#196]
I recently had some pydpiper executors die due to scinet's ongoing filesystem issues:
```
PBS Job Id: 27646268.gpc-sched-ib0
Job Name:   registration_chain.py-executor
Exec host:  gpc-f106n032-ib0/0+gpc-f106n032-ib0/1+gpc-f106n032-ib0/2+gpc-f106n032-ib0/3+gpc-f106n032-ib0/4+gpc-f106n032-ib0/5+gpc-f106n032-ib0/6+gpc-f106n032-ib0/7
An error has occurred processing your job, see below.
Post job file processing error; job 27646268.gpc-sched-ib0 on host gpc-f106n032-ib0/0+gpc-f106n032-ib0/1+gpc-f106n032-ib0/2+gpc-f106n032-ib0/3+gpc-f106n032-ib0/4+gpc-f106n032-ib0/5+gpc-f106n032-ib0/6+gpc-f106n032-ib0/7

Unable to copy file /var/spool/torque/spool/27646268.gpc-sched-ib0.OU to gumae@gpc-f102n084-ib0:/home/m/mchakrav/gumae/scratch/D3KO/registration-chain/registration_chain.py-executor-1-20150309-115836291186.job-o.log, error 1
*** error from copy
/var/spool/torque/spool/27646268.gpc-sched-ib0.OU: No such file or directory
*** end error output

Unable to copy file /var/spool/torque/spool/27646268.gpc-sched-ib0.ER to gumae@gpc-f102n084-ib0:/home/m/mchakrav/gumae/scratch/D3KO/registration-chain/registration_chain.py-executor-1-20150309-115836291186.job-e.log, error 1
*** error from copy
/var/spool/torque/spool/27646268.gpc-sched-ib0.ER: No such file or directory
*** end error output
```

This is in no way pydpiper's fault, but that executor is lost and so the pipeline is slower than it should be.

Is there a method to resubmit the executors that died to try again?

**Comment by bcdarwin** [comment]
In principle, you should be able to call pipeline_executor.py with --uri-file=... --num-executors=... --time=..., but I've just discovered that this is broken due to one of Python's principle advantages (runtime type error).  Until it's fixed, you could call qsub on your pbs-jobs files, e.g.

    qsub -V -o LSQ6.py-executor-6-20150309-184343726171.job-o.log -e LSQ6.py-executor-6-20150309-184343726171.job-e.log xyz.job

with some reasonable values for the time or whatever (e.g., using the `date` command with some format string).

**Comment by gdevenyi** [comment]
Does the referenced commit fix the submission process as defined above?

**Comment by bcdarwin** [comment]
Yes.  In doing this 'by hand', you give up some of Pydpiper's guesses about how many executors it should submit and so on, so it's not as good as a real restart, but if you just need a few more executors for some reason, it should work.

**Comment by gdevenyi** [comment]
That's exactly what I'm looking for. Thanks!
