### ISSUE TITLE
atlas_to_atlas

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/pydpiper#205]
Hey all,

I am wondering if in MBM or pydpiper there is code for atlas_to_atlas registrations. MBM gives you a nice average of all your registered input data but then no way to align that to the wonderful atlases out there? Or am I missing something? I know there is MAGeT but its not for all instances. Wondering if there is a recommendation here? or a file/code snippet/flag I am not seeing?

Thanks,

Patrick

**Comment by jasonlerch** [comment]
MAGeT can work for pretty much all instances - I use it for single atlas to atlas registration all the time. Specify an atlas folder containing a single atlas, and provide a single image input.

**Comment by psteadman** [comment]
Of course yes! Thanks!
