### ISSUE TITLE
executors can die on SciNet due to the uri file not being created

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#206]
Dulcie recently ran a pipeline on 232 brains, and it took the server over half an hour to start:

[2015-04-13 23:27:39.950,pydpiper.application,INFO] Calling `start`
[2015-04-13 23:27:40.965,pydpiper.application,INFO] Command is: ...
[2015-04-13 23:27:41.064,pydpiper.application,INFO] Command version : 1.11
[2015-04-13 23:46:19.840,atoms_and_modules.registration_functions,INFO] No mask ...
[2015-04-13 23:58:48.430,pydpiper.pipeline,INFO] Create Edges time: 3.63106584549
[2015-04-13 23:58:50.655,pydpiper.pipeline,INFO] Graph heads: [0, 1, 2, 3, 4, 5, 6, 7, ...
[2015-04-14 00:00:20.662,pydpiper.application,INFO] Starting pipeline daemon...
[2015-04-14 00:00:20.793,pydpiper.pipeline,INFO] Finished stages log doesn't exist or is corrupt.
[2015-04-14 00:04:33.824,Pyro4.multiplexserver,INFO] starting multiplexed socketserver
[2015-04-14 00:04:33.843,pydpiper.pipeline,INFO] Daemon is running at: 10.20.118.64:35755
[2015-04-14 00:04:33.844,pydpiper.pipeline,INFO] The pipeline's uri is: ...
[2015-04-14 00:04:36.114,Pyro4.core,INFO] daemon 10.20.118.64:35755 entering requestloop

So even though the graph took only about 4 seconds to be created, the uri file was created at 00:04 about 37 minutes after the program started. By this time all the executors had died because they couldn't find the uri file when they started:

MBM.py-executor-54-20150413-183027314220.job.log:[2015-04-13 23:31:04.508,__main__,ERROR] Problem opening the specified uri file:

We should investigate this long start-up and be more robust against it in terms of the executors.

**Comment by gdevenyi** [comment]
I have also ran into this, scinet seems to have some serious filesystem issues under loading, causing serious delays with as simple commands as "ls", this is probably the root cause.

Perhaps the executor jobs could be set to a "user hold" and then once the executor starts they could be released?

**Comment by bcdarwin** [comment]
The problem is that the server can't directly manage holds - you have to ssh into a dev node which is pretty SciNet-specific (although so is our server submission process...).

A worse way of doing this is to wait for the file to be modified if it doesn't exist or trying to connect fails (if it's from an old run), but in this case you run into the situation where if the server crashes/is killed right away the executors may continue for some time.  A messy situation ... perhaps bringing back the nameserver might offer some modest simplification.

**Comment by mcvaneede** [comment]
Jason mentioned that we should check how much I/O access is being done in the setup, and whether this is more likely to happen when the server is first run as opposed to a "restart" when a second or third round of server/executors comes on.

If it is I/O related, we will also have to keep in mind that in later versions of pydpiper, all input files are checked to make sure they are proper MINC files (and that there are no duplicates). Which could make it more likely to happen.

A solution could then be to have the I/O related stuff be run at the submit node, prior to launching the server/executor jobs.

**Comment by mcvaneede** [comment]
I've rerun the command that Dulcie was running (the pipeline with 232 brains), and in the rerun the setup completed within 2 minutes. I copied the input files to a different location, and ran the pipeline in a different directory as well. This suggests that this is not inherently a pydpiper issue, but that it has to do with random latencies at SciNet.

For now (unless we find out that this happens very often) we should simply re-instate the time-to-seppuku on SciNet (to make sure that the idle executors die at some point), and have the server start the local executor only after it's done with its initialization.
