### ISSUE TITLE
Backend simplification

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#210]
At some point we switched from threads to processes in the server due to #136.  However, it appears that a fix does exist in the form of the subprocess32 module (backport from Python 3).  Thus, using this module (or a modern Python) would allow us to revert some complicated process-related changes to the server, which would have the side benefit of eliminating the extraneous zombie Python processes which sometimes remain when running executors locally.

(In the long run, it might be better to switch to a Python grid library such as [gridmap](https://github.com/pygridtools/gridmap), [saga-python](https://github.com/radical-cybertools/saga-python)/[pilot](http://radical-cybertools.github.io/radical-pilot/index.html), [WorkQueue](http://ccl.cse.nd.edu/software/workqueue/)/[Makeflow](http://ccl.cse.nd.edu/software/makeflow/), or [JobTree](https://github.com/benedictpaten/jobTree).)

**Comment by mcvaneede** [comment]
You did this my dear fellow!
