### ISSUE TITLE
generalize sge_batch arguments

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#215]
Currently sge_batch's functionality is too limited as it doesn't allow passing on arbitrary options to qsub, so really only serves to pipe scripts without first creating a file, which means that, e.g., collaborators with different queueing setups can't specify the needed options.  It should be generalized and possibly moved out of the Pydpiper repository as it's not really specific to it.

**Comment by gdevenyi** [comment]
I agree, I have to modify sge_batch when I install here to get it to work with our setup.

May I suggest a way to provide a template file that pydpiper will use on sge systems?

**Comment by bcdarwin** [comment]
Go ahead!  I'm guessing something like adding a --sge-header-file=... with some Bash templating system that supports variable interpolation?

Strictly speaking, we ought to distinguish not between SGE and PBS but between 'normal' and 'headless' (i.e., where we submit the server as a job) operation, but that's another can of worms ...

**Comment by bcdarwin** [comment]
PydPiper no longer uses sge_batch, which has moved to minc-stuffs.

In the current develop branch you can pass --queue-opts="..." which will be sent directly to qsub.
