### ISSUE TITLE
Make two-level and registration chain accept 1-column CSV file instead of current format

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#217]
to be consistent with R convention and in particular the format used with RMINC for statistical analysis, removing the need to generate a new CSV in 'wide' format by hand.

**Comment by gdevenyi** [comment]
Is the current format the same as the format for registration_chain.py?

I'd like to try this but I can't find any docs.

**Comment by bcdarwin** [comment]
Yeah, one row of comma-separated files per subject.

**Comment by mcvaneede** [comment]
Done
