### ISSUE TITLE
SGE hardcoded option of "-pe smp" assumes that all SGE installations are setup the same

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#219]
I don't have a -pe named SMP, when pydpiper used sge_batch, I could edit it, now I need to re-compile/install pydpiper

With the addition of --queue-opts can *all* settings be stored in that string so that I can modify it from the default?

**Comment by bcdarwin** [comment]
I've added a `--pe` option in the develop branch (78722daf05) ... since the options we have are set programmatically I'm reluctant to open them fully, although I suppose you could take the difference of the keys between then generated and user-supplied strings ...

**Comment by gdevenyi** [comment]
Just want to follow up here, looks like -l vf= is also hard-coded as the memory request variable.

This is a non-standard consumable, the default one is h_vmem on most clusters.

**Comment by jasonlerch** [comment]
Going from memory here, but I thought that h_vmem corresponds to the actual virtual memory available at the time of submission. The consumable we create is independent of actual virtual memory; the reason being that we might know that a running job will consume more memory at some point than it would at the beginning, so relying on h_vmem would result in overcommitting existing memory.

(But my memory might be faulty …)

**Comment by gdevenyi** [comment]
Ah, I see why you might want to do that, but I don't have that configured on my cluster, I use h_vmem so strictly control memory usage of jobs. This is particularly important because desktops are part of the cluster and so I want fewer running on a per-machine basis whenever possible.

The main problem is that since pydpiper is requesting a resource that doesn't exist on my cluster, the jobs can never be scheduled/run.

**Comment by mcvaneede** [comment]
I've opened up an argument that you can use to change the memory request variable:

--mem-request-variable

It's part of the latest release (https://github.com/Mouse-Imaging-Centre/pydpiper/releases/tag/v1.15)

**Comment by gdevenyi** [comment]
Cheers, will test.

Can any command-line setting be adjusted to be a config file variable by omitting the "--"? If so, I'll make a CIC.cfg to set the default for pydpiper here.

**Comment by bcdarwin** [comment]
Almost any, except for a few like the location of the config file.  In fact, you can even leave the "--" if you prefer, courtesy of the `configargparse` library.
