### ISSUE TITLE
Memory usage of the server is unreasonable

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#220]
We were running a twolevel_model_building.py and found that the node where the server and executor were running on crashed because of an overuse in memory. Some messages from the pipeline.log associated with this are:

```
Traceback (most recent call last):
  File "/project/j/jlerch/bcdarwin/pydpiper-dev/lib/python2.7/site-packages/pydpiper-1.14_beta2-py2.7.egg/pydpiper/pipeline_executor.py", line 207, in runStage
    process = subprocess.Popen(args, stdout=of, stderr=of, shell=False)
  File "/scinet/gpc/tools/Python/Python278-shared-intel/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/scinet/gpc/tools/Python/Python278-shared-intel/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

What we found in terms memory usage (version 1.14-beta2) is:
Number of stages in the pipeline: 1115733
Server memory used: 8.7G
Number of stages in the pipeline: 332496
Server memory used: 2.5G

These are rough estimates, but good to keep in mind for now...

**Comment by bcdarwin** [comment]
So accumulating all stages from a large (1.1m stages) into a list takes up ~5G, so it's easy to understand why memory usage is so large.

It seems like a substantial part of this is from the overhead of individual objects, particularly strings (37 bytes per empty string; note that each shell command is stored as a list of strings!).  An easy (partial) fix would be to [intern](https://docs.python.org/2/library/functions.html#intern) these strings at stage creation time.

**Comment by mcvaneede** [comment]
Command strings have been intern-ed.
