### ISSUE TITLE
Way to pass evironement variables into executors?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#221]
I have some very high resolution data and when mincblur runs, it is exhausting the space on /tmp due to the old unix philosophy of separate partitions and all that. I understand that mincblur will honour TMPDIR which I'd like to /scratch, a much bigger local storage space, just setting this variable before calling MBM.py doesn't seem to work, is there another way?

**Comment by bcdarwin** [comment]
Pydpiper currently should send through any environment variables you supply; it seems like the mincblur on our systems (as of mni_autoreg 0.99.60) doesn't respect this variable.

We should probably inline the current environment into the shell scripts generated when you run a command ...

**Comment by gdevenyi** [comment]
Hrm, also using 0.99.60, maybe this is the issue.

**Comment by mcvaneede** [comment]
Not a pydpiper related bug...
