### ISSUE TITLE
What determines if a pipeline will restart?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#224]
I had a pipeline with partially finished stages and a runscript that I had been using. I moved the whole directory to a different place and when I ran it again, it said 0 completed stages and started from the beginning, losing all the work I had done.

What determines when a pipeline restarts?

**Comment by bcdarwin** [comment]
A stage is considered previously completed if a stage with exactly the same shell command has already run (as recorded in the finished-stages file), and every stage it depends on has also previously completed.

In your case, all filenames have changed, so everything re-ran.

Nipype provides a command to relocate a pipeline for (iirc) essentially this reason.  Another possibility would be to go to all relative paths, or at least ignore the cwd part of the path from stage comparisons.

We've also been thinking about not allowing the pipeline to be run without some --clobber option or similar if things have changed.

**Comment by gdevenyi** [comment]
I like the working directory pruning option, I wouldn't have expected the absolute path to be stored in the pipeline.

**Comment by bcdarwin** [comment]
Relative paths have landed in df005b62.  (If you haven't noticed, we've mostly finished completely rewriting Pydpiper's pipeline scripting system, but not yet pipelines, to make writing pipelines easier.)

Still, I think the pipeline shouldn't completely forget its previous state and start overwriting everything without warning if something has changed.  (This also applies in the case when the stage storage format changes between versions!)

**Comment by mcvaneede** [comment]
We now use relative paths, so this should work.
