### ISSUE TITLE
Default MAGeT protocol filenes of SciNet don't exist

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#226]
From the help:

```
  --lsq12-protocol LSQ12_PROTOCOL
                        Can optionally specify a registration protocol that is
                        different from defaults. Parameters must be specified
                        as in the following example: applications_testing/test
                        _data/minctracc_example_linear_protocol.csv [Default =
                        /projects/mice/share/arch/linux-3_2_0-36-generic-
                        x86_64-eglibc-2_15/src/pydpiper/applications_testing/t
                        est_data/default_linear_MAGeT_prot.csv].
  --nlin-protocol NLIN_PROTOCOL
                        Can optionally specify a registration protocol that is
                        different from defaults. Parameters must be specified
                        as in either or the following examples: applications_t
                        esting/test_data/minctracc_example_nlin_protocol.csv a
                        pplications_testing/test_data/mincANTS_example_nlin_pr
                        otocol.csv [Default = /projects/mice/share/arch/linux-
                        3_2_0-36-generic-x86_64-eglibc-2_15/src/pydpiper/appli
                        cations_testing/test_data/default_nlin_MAGeT_minctracc
                        _prot.csv]
```

**Comment by mcvaneede** [comment]
For now I can give you a direct link to where some of the source is on SciNet:

/project/j/jlerch/matthijs/pydpiper_modules/src/pydpiper/applications_testing/test_data

but that should be fixed properly...

**Comment by bcdarwin** [comment]
Really, this is just a hack and should be removed from the code.  We should add these to the site config file instead, but I don't know much about how to make setuptools do this automatically ...

**Comment by gdevenyi** [comment]
Adding this to the install would be helpful as I have to manually specify the filenames on my local cluster too

**Comment by gdevenyi** [comment]
Followup, I realized, I can't specify these files in a site-specific config file, because --lsq12-protocol and --nlin-protocol are also used for MBM and other tools. I think the option for this may need to change in order to specify it.

**Comment by mcvaneede** [comment]
In the MBM pipeline you can now specify:

--lsq12-protocol

for the main pipeline and:

--maget-lsq12-protocol

for the MAGeT part of the pipeline. You're not able to specify these in a generic config file, because not all pipelines know about these flags, but you can load a separate config file for MAGeT.
