### ISSUE TITLE
spawn: exec of minc_modify_header failed: Argument list too long in nuc* stages

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#230]
I'm having some trouble with MBM.py failing with the error:
```
      10 spawn: exec of minc_modify_header failed: Argument list too long
      11 nu_evaluate: crashed while running minc_modify_header (termination status=65280)
```

Not sure how to go about debugging this. Thoughts?

**Comment by bcdarwin** [comment]
Maybe look in the pipeline_stages file for the offending nu_evaluate stage ... the relevant stage number should be available from the error (either in pipeline.log or the relevant stage logfile), and try running it by hand?

**Comment by bcdarwin** [comment]
Apparently the size of `envp` also matters. Pydpiper uses `qsub -V` to ship the entire env to the grid; is it possible you have some huge shell functions defined in your environment or something?

**Comment by vfonov** [comment]
happens when there is a huge :history attribute (from dcm2mnc for example). The easiest way to fix this issue is to wipe it clean.

**Comment by gdevenyi** [comment]
Thanks @vfonov it is indeed very long.

Perhaps pydpiper needs a check for this in the future?

**Comment by bcdarwin** [comment]
Possibly, but the real fix would be for minc_modify_header to give a better error message.  This sort of thing seems to happen sufficiently infrequently that I don't know if it would justify making more system calls at pipeline start -- this already takes forever on SciNet...

**Comment by vfonov** [comment]
it's not a problem of minc_modify_header - it's a limitation of system call from perl ( nu_evaluate) . It reads :history from the minc file, adds a new line and tries to put it all back together by making a call to minc_modify_header.

**Comment by bcdarwin** [comment]
Actually, I guess it's not technically minc_modify_header that does this, so not sure how to check for it in general ...

**Comment by gdevenyi** [comment]
Not a pydpiper bug.
