### ISSUE TITLE
Docs for anatGetAll csv format?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#233]
I'd like to distribute a RMINC anatgetall style CSV with our human magetbrain labels, are there docs somewhere I can use to construct one?

Thanks!

**Comment by cfhammill** [comment]
The basic format of the Dorr atlas we use in house is a 3-column comma separated file. The first column is the structures included in the atlas, the second column is the labels for the right hemisphere, and the third is the labels from the right hemisphere. 

Structure                                        | right.label   | left.label
--------------                                     | -------------- | -------------
amydala                                         |   51            | 151
anterior commisure: pars anterior | 115            | 215 

The column names are used in the anatGetAll code so they are important. Internally anatGetAll uses vanilla read.csv, so you can check that it reads in correctly with that. Is that enough to go on or would you like more details?

**Comment by gdevenyi** [comment]
Looking at the csv that travels the Dorr atlas, other columns are ignored by anatGetAll? My csv copy also has "Num" "hierarchy" and "tissue type"

If that's all, that's super simple, I'll get right to making CoBrALab files and testing.

**Comment by cfhammill** [comment]
It appears that the code ignores all other columns, it references Structure, right.label, and left.label exclusively by name, so it looks as though the order doesn't matter either, just so long as it has those three column names.

**Comment by jasonlerch** [comment]
The ‘tissue type’ column is used for the thickness code. The hierarchy is not yet used, but relates to (unimplemented plans) to deal with hierarchies in anatomy.

Jason
