### ISSUE TITLE
Queue specifications on PBS systems

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/pydpiper#234]
I see in the NEWS that the --queue option was removed, however it appears to still exist???? Perhaps its lost its function

The reason I ask is on Sickkids HPF executors are submitted automatically to the all queue which has a max wall time of 24:59:59 and it appears some of my jobs need some more time. 

How can I get my executors submitted to a different queue? I couldnt easily locate where the executor job submission files are or how to specify this.

**Comment by bcdarwin** [comment]
--queue-name

________________________________________

**Comment by psteadman** [comment]
Yes yes that was a confusion on my part. --queue was removed but --queue-name remains but yet doesnt appear to be respected in 1.15, it was in 1.13.1 for example this call
``` sh
BM.py --mem 85 --greedy --queue-name long --uri-file /home/pstead/uri_20160201v1 --prologue-file /home/pstead/piper-files/prologueCRISPY.sh --queue-type pbs --time 108:00:00 --output-dir=/hpf/largeprojects/pfrankla/pstead/20151215set_pipes --pipeline-name=20160201v1_arcT_20151215set_combined --lsq6-target=/hpf/largeprojects/pfrankla/pstead/input/mnc-set1_20151215_combined_20160119/101_3_ln.mnc --lsq6-simple --no-calc-stats --no-nuc --no-inormalize --verbose --num-executors=8 --registration-method minctracc --verbose /hpf/largeprojects/pfrankla/pstead/input/mnc-set1_20151215_combined_20160119/*ln.mnc
```
submits all my jobs to the queue -all. You might not know but I figure i should ask anyways. 

pstead@hpf26[~]$ qstat -u pstead

moab8master.hpf.cluster: 
                                                                                  Req'd    Req'd       Elap
Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory   Time    S   Time
----------------------- ----------- -------- ---------------- ------ ----- ------ ------ --------- - ---------
3343566                 pstead      all      MBM.py-pipeline- 146225     1      1   85gb       --  R  00:54:04
3343567                 pstead      all      MBM.py-pipeline- 196153     1      1   85gb       --  R  00:54:04
3343568                 pstead      all      MBM.py-pipeline- 173789     1      1   85gb       --  C       -- 
3343569                 pstead      all      MBM.py-pipeline- 136476     1      1   85gb       --  R  00:54:04
3343570                 pstead      all      MBM.py-pipeline- 199960     1      1   85gb       --  C       -- 
3343571                 pstead      all      MBM.py-pipeline-  45730     1      1   85gb       --  R  00:54:04
3343572                 pstead      all      MBM.py-pipeline-  49073     1      1   85gb       --  R  00:54:04
3343573                 pstead      all      MBM.py-pipeline- 209580     1      1   85gb       --  R  00:54:04
3343575                 pstead      all      MBM.py-pipeline- 186810     1      1   17gb       --  R  00:52:40
3343574                 pstead      all      MBM.py-pipeline- 118664     1      1   17gb       --  R  00:52:40
3343576                 pstead      all      MBM.py-pipeline-  50847     1      1   17gb       --  R  00:52:40
3343577                 pstead      all      MBM.py-pipeline- 143475     1      1   17gb       --  R  00:52:40
3343578                 pstead      all      MBM.py-pipeline- 185817     1      1   17gb       --  R  00:52:40
3343579                 pstead      all      MBM.py-pipeline-  88170     1      1   17gb       --  R  00:52:40
3343581                 pstead      all      MBM.py-pipeline-  24779     1      1   17gb       --  R  00:52:40
3343580                 pstead      all      MBM.py-pipeline- 145895     1      1   17gb       --  R  00:52:40
3343583                 pstead      all      MBM.py-pipeline- 146274     1      1   17gb       --  R  00:52:40
3343582                 pstead      all      MBM.py-pipeline- 172351     1      1   17gb       --  R  00:52:40

**Comment by bcdarwin** [comment]
OK, fixed.  Note that the 1.15 installed on the system is actually the 1.15 'release' plus some HPF-related modifications - should be called 1.16-beta or something (sorry about that).  Note that because of these changes, you're really running single-core executors with 85gb of RAM.  If you want to go back to the SciNet-style of running, you now need `--submit-server`, otherwise decrease your memory requirement to something like 10g.

**Comment by bcdarwin** [comment]
Oh, and without `--submit-server` the prologue file won't be honoured -- didn't bother adding this to the new configuration since I didn't think anyone was using it.  I'll fix this soon.  Since we pass all environment variables to the queue, the only thing you probably need from yours is the TMPDIR line, though.

**Comment by bcdarwin** [comment]
Note that sufficiently long jobs should be assigned to the `long` queue automatically, so if you don't see

```
qsub: submit error (Job exceeds queue resource limits MSG=cannot satisfy queue max walltime requirement)
```

then things are probably fine (or you're not submitting jobs as long as you think for some reason).

**Comment by psteadman** [comment]
Thanks for the input here. I still think there are some issues. It appears that depending on how you submit/run your pipeline different flags are respected. I think there needs documentation on this. You raise the example of prologue files and env variables. I also would like to raise the example of --submit-server that then doesnt respect --time --mem --default-job-mem but does respect --queue-name. 

Essentially I want to submit a job that requests sufficient memory (which I specify) and a specific run time. My fear is my jobs are getting killed because they hit the 24:59:59 mark on all queue. The log files in the version 1.13.1 would spit out job exceeded wall time but I dont see that in the runs of the new queue. Despite this something is ending in these jobs where the registration has not finished. 

I was using --greedy and --mem 85 because my jobs were getting killed for using nearly 50G of ram. It is odd as I havent seen minctracc use so much ram before but it is the second last registration stage. 

Any thoughts would be helpful.

**Comment by bcdarwin** [comment]
You are right that many issues remain.  I guess the overarching issue here is that PydPiper instantiates new copies of itself in various weird ways involving reshuffling its own command-line flags based on its current and intended states.  That's a boring implementation detail, but getting consistent semantics is a challenge.  For instance, how should the prologue file be used?  Should it be inlined into any queue submission script (the original intent), or run before any server start and/or any executor start (all of which involve annoying details about the topology of your execution)?  You could imagine a further proliferation of options, which aren't fun to deal with in bash (or argparse ...).

The memory issue is interesting.  I haven't used `--submit-server` on hpf before, but I'm currently dealing with memory-related issues -- the scheduler's memory accounting uses vmem, which is extremely conservative (if a server runs an executor in a separate process, that process is credited with using the full amount of memory of its parent, etc., even though physically this memory is actually mostly shared).

**Comment by mcvaneede** [comment]
Executor time limits can be set through the --time flag.

Reopen if other parts of the issue still exist!
