### ISSUE TITLE
twolevel_model_building.py fails for the case of subjects with a single timepoint

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#235]
Given that this a longitudinal pipeline, it's probably not sensible to have single-timepoints in it, but right now, they're accepted and fail at the lsq12 xfmavg stage.

I would presume either the pipeline to handle them gracefully somehow, or by warning and refusing to run.

**Comment by bcdarwin** [comment]
This should now fail at startup.
