### ISSUE TITLE
pipeline_executor.py bug

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/pydpiper#239]
Hello everyone,

I would submit a pull request but I am not sure which is the current dev branch (develop or new-pydpiper) but in [pydpiper/pipeline_executor.py](https://github.com/Mouse-Imaging-Centre/pydpiper/blob/master/pydpiper/pipeline_executor.py#L620) you have an error on line 688 (HPF versions) or 620 (master version here) with `pe.submitToQueue()` this needs to be `pe.submitToQueue(i)` based on my read of the code. `submitToQueue()` requires 2 inputs, itself and number.

Found this bug when trying to submit executors using pipeline_executor.py blah blah

Tell me if i've got this wrong. May be specific to the version on the HPF.

**Comment by bcdarwin** [comment]
Fixed.
