### ISSUE TITLE
Question: What's the role of --mem if pydpiper is supposed to estimate memory usage?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#249]
It seems there's been a big push to add memory estimation to various stages but I still have to specify memory for job submission, this is confusing, shouldn't jobs be submitted with the amount of memory required?

**Comment by bcdarwin** [comment]
Right now this flag roughly corresponds to the maximum an executor can request ... in principle we could remove it, but (i) users are sometimes confused if the scheduler rejects their jobs for unclear reasons, (ii) you can currently use this flag in combination with others (--greedy) to force certain executor behaviour, e.g., for long-running executors on SciNet ...

**Comment by gdevenyi** [comment]
So, if I push this up to 47G (the largest nodes on my cluster) I shouldn't see executors requesting 47G unless they really need it (or I add greedy?)

**Comment by bcdarwin** [comment]
That's true for the usual mode of use where you run the server on a local node, though not necessarily SciNet-style.

**Comment by gdevenyi** [comment]
Cheers, thanks!
