### ISSUE TITLE
MaGeT.py -- odd checkerboarding in voted segmentation

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#252]
Running v1.18.1, I run into this odd error:
![volumetric_problem_sub4364](https://cloud.githubusercontent.com/assets/3001850/17569141/f4c7c536-5f14-11e6-9e56-aff452b07cb7.png)

Has anyone run into this before? About 85% of the subjects in this run show this.

**Comment by bcdarwin** [comment]
I don't think this is a Pydpiper issue.  It's more likely related to voxel_vote or Pyminc.  Not sure whether it's recently introduced or not ... have you changed the initial model, template library, or anything?

**Comment by gdevenyi** [comment]
I haven't made any adjustments yet, we're using DorrSteadManUllman which we've previously had no issues with.

Versions of all tools:
  1) quarantine                                2) minc-toolkit/1.9.11                       3) anaconda/2.3                              4) pyminc/0.47                               5) minc-stuffs/0.1.15a^minc-toolkit-1.9.11   6) pydpiper/1.18

**Comment by bcdarwin** [comment]
My guess is this is a Pyminc bug.  Could you try downgrading Pyminc, say to 0.45?

Also, what's the "^" -- are you using Spack or similar?

**Comment by gdevenyi** [comment]
Okay will retry.

Do you happen to know how to reset the pipeline to that stage?

As for '^', that's just my name for my environment-modules version of the build dependencies I used, in case I have multiple versions.

**Comment by bcdarwin** [comment]
At the moment you have to do it by hand by deleting the stage from the `_finished_stages` file.  It's not ideal...we should rethink the way pydpiper is run, but ...

**Comment by gdevenyi** [comment]
Note for future people:
```sh
for ID in $(grep voxel_vote pipeline.log  | grep -E -o 'Stage [0-9]+' | cut -d" " -f 2); do
sed -i "s/${ID}//g" *_finished_stages
done
```

**Comment by gdevenyi** [comment]
False alarm, issue is with new Display rendering. Redirecting to the right place.
