### ISSUE TITLE
zipping of pydpiper install directory?

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#268]
The way Pydpiper is currently installed by default produces a lib/python/pydpiper-2.0-py3.5.egg file, which is a zipped directory containing code and data files.  Zipping this (which can be controlled by setting the `zip_safe` argument to `setup`) allows faster load times at the cost of not being able to refer to a path to the data files.  Since we currently bundle several config files and protocols with the code, is it worth the performance hit (lots of NFS reads etc., whenever we start a server/executor...) to have easy access to these files?

**Comment by mcvaneede** [comment]
Do you know anything about the performance differences? I think the zipped directory is pretty annoying.

**Comment by bcdarwin** [comment]
Lots of file reads on every import of pydpiper ... worse (and more evil) on big clusters with slow file I/O, I guess.  Don't know numbers though ...

**Comment by gdevenyi** [comment]
I found it to be pretty epicly slow to fire up here. Even for just ``--help``

**Comment by bcdarwin** [comment]
Did your install zip this directory?  There's also slowness from the Python interpreter startup, which involves looking at thousands of locations on the PYTHONPATH that MIGHT have files, and from loading the other libraries, so maybe any difference would actually be washed out.

**Comment by bcdarwin** [comment]
Launching many instances of Python in parallel on grids is a known way to cripple your network file system (see, e.g., http://conference.scipy.org/proceedings/scipy2016/yu_feng.html)

**Comment by gdevenyi** [comment]
It looks like it's an .egg file.

**Comment by bcdarwin** [comment]
OK, then this fix probably wouldn't help you (unless unzipping into RAM is slower than reading from FS)

**Comment by gdevenyi** [comment]
Okay, probably all the dependencies getting read over the NFS from the anaconda install.

**Comment by bcdarwin** [comment]
since there are only a few files in Pydpiper I've set zip_safe=False
