### ISSUE TITLE
twolevel_model_building protocols

### ISSUE THREAD

**Issue by DJFernandes** [Mouse-Imaging-Centre/pydpiper#285]
I seem to be having issues with protocols:
First, I ran...
`twolevel_model_building.py --pipeline-name=exp1 --num-executors=40 --init-model=/hpf/largeprojects/MICe/tools/initial-models/Pydpiper-pride-of-models/p36/p36_MEMRI_mouse_brain.mnc --registration-method=mincANTS  --csv-file files.csv`

and got the following error:

`NotImplementedError: ('You need to supply a protocol at the moment.  Sorry!', 'occurred at index 0')`

I then ran...
`twolevel_model_building.py --pipeline-name=exp1 --num-executors=40 --init-model=/hpf/largeprojects/MICe/tools/initial-models/Pydpiper-pride-of-models/p36/p36_MEMRI_mouse_brain.mnc --registration-method=mincANTS --lsq6-protocol /hpf/largeprojects/MICe/tools/protocols/linear/Pydpiper_in_vivo_scans_minctracc_center_estimation.csv --lsq12-protocol /hpf/largeprojects/MICe/tools/protocols/linear/Pydpiper_testing_default_lsq12.csv --nlin-protocol /hpf/largeprojects/MICe/tools/protocols/nonlinear/Pydpiper_mincANTS_standard_90_micron.pl --csv-file files.csv`

and 

`twolevel_model_building.py --pipeline-name=exp1 --num-executors=40 --init-model=/hpf/largeprojects/MICe/tools/initial-models/Pydpiper-pride-of-models/p36/p36_MEMRI_mouse_brain.mnc --registration-method=mincANTS --lsq6-protocol /hpf/largeprojects/MICe/tools/protocols/linear/Pydpiper_in_vivo_scans_minctracc_center_estimation.csv --lsq12-protocol /hpf/largeprojects/MICe/tools/protocols/linear/Pydpiper_testing_default_lsq12.csv --csv-file files.csv`

and

`twolevel_model_building.py --pipeline-name=exp1 --num-executors=40 --init-model=/hpf/largeprojects/MICe/tools/initial-models/Pydpiper-pride-of-models/p36/p36_MEMRI_mouse_brain.mnc --registration-method=mincANTS --lsq12-protocol /hpf/largeprojects/MICe/tools/protocols/linear/Pydpiper_testing_default_lsq12.csv --csv-file files.csv`

All of which gave me a different error:
`ValueError: I'd use the MAGeT nlin protocol for masking as well but different programs are specified`

Which protocols should I be using?

Directory to replicate my commands is here:
/hpf/largeprojects/MICe/dfernandes/social_behaviour_study/exp1/registration/two_level_pydpyper

**Comment by bcdarwin** [comment]
--lsq12-protocol, --nlin-protocol, and --maget-nlin-protocol (or to use the same mincANTS protocol as for the nonlinear part of the build model, set --maget-registration-method=mincANTS, but this probably isn't what you want)

**Comment by bcdarwin** [comment]
Closing since this is encompassed by #264, but post here if there are more issues.

**Comment by DJFernandes** [comment]
Thanks.
The --no-run-maget flag worked for me (I didn't want to run maget).
