### ISSUE TITLE
transforms.csv: difference between lsq12_nlin_xfm and overall_xfm?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#290]
I'm using a bootstrapped pydpiper2 run to move resting state data into a common space.

I'm wondering which of the transforms in the CSV is appropriate to bring a scan into the common space.

Thanks!

**Comment by bcdarwin** [comment]
The overall_xfm includes the rigid native->standard part of the transformation.

**Comment by bcdarwin** [comment]
The scans given to pydpiper should be resampled into the new model space by Pydpiper.  If you are trying to resample, e.g., other modalities aligned to your input images, use the overall_xfm.

**Comment by gdevenyi** [comment]
Cheers thanks!
