### ISSUE TITLE
address xfmavg bug

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#295]
see http://www.bic.mni.mcgill.ca/pipermail/minc-users/2016-February/004277.html

**Comment by mcvaneede** [comment]
So this turns out not to be an issue for us right?

**Comment by bcdarwin** [comment]
I ran xfmavg_scipy.py on the transforms from one pipeline and got the same results as with xfmavg (to numerical precision).  I don't know what we can conclude from that ...

**Comment by gdevenyi** [comment]
For me, this was just an issue with lsq6 transforms.
