### ISSUE TITLE
Ability to use user-generated masks in 2.0?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#298]
I recall being able to supply masks in 1.0 versions but I can't find the option to specify that anymore, is it still an option somewhere?

**Comment by bcdarwin** [comment]
Looks like I forgot to add that.

What's the best way: a directory full of masks named after the input files?  A CSV with an additional 'mask' column?  (I'm starting to think all pipelines should take csvs as input.)

**Comment by gdevenyi** [comment]
I like the CSV input. I think it encourages reproducibility compared to a file glob

**Comment by bcdarwin** [comment]
@mcvaneede ?

**Comment by cfhammill** [comment]
I vote yes, data frames are the way

**Comment by mcvaneede** [comment]
I'd say CSVs as well

**Comment by bcdarwin** [comment]
As of e85c586d2 both MBM and MAGeT accept .csv files which take `file` and optional `mask_file` columns.  You should also be able to leave some masks blank if you don't have any, but at this point those files may just not be masked.

**Comment by bcdarwin** [comment]
edit: also, these basically get overriden in the pipeline, so currently only useful if your files wouldn't otherwise be masked.  I guess the default should be that no pipeline component overrides an existing mask, only adds one?
