### ISSUE TITLE
[Feature Request] Pass a list of files for asymmetry pipeline

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/pydpiper#299]
It would be nice to be able to pass a list of files to the asymmetry pipeline (and any other that lacks
this ability), keeps the command line simpler and more readable especially with many files.

**Comment by bcdarwin** [comment]
True; quick workaround: asymmetry.py --files $(cat files.txt) <...>

**Comment by cfhammill** [comment]
I had considered doing that, but then command and version still has all the filenames.
