### ISSUE TITLE
Fails to shut down executors for clean exit after Pipeline completion

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/pydpiper#30]
After completion of a pipeline the Daemon does not shut down the executors when run on SGE. I have not tested this on pbs.
There seems to be hanging at the stage before it makes serverShutdownCall. Jobs remain running on SGE until ctrl-C or qdel is called in a separate shell.

Example bash output is below:
Example 1 - no executor shutdown
Pipeline completed. Daemon unregistering 2 client(s) and shutting down...

Example 2 - partial executor shut down
Pipeline completed. Daemon unregistering 4 client(s) and shutting down...
Made serverShutdownCall to: PYRO://172.16.1.34:7766/ac10012242db1eb713c718a17a4f1a5808
Client deregistered from server: PYRO://172.16.1.34:7766/ac10012242db1eb713c718a17a4f1a5808
Made serverShutdownCall to: PYRO://172.16.1.34:7767/ac10012242dc1eb713c718a17a4fc20639
Client deregistered from server: PYRO://172.16.1.34:7767/ac10012242dc1eb713c718a17a4fc20639

**Comment by jasonlerch** [comment]
FIxed
