### ISSUE TITLE
Howto: Transform atlas mask onto final nlin for v1.x series

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#301]
Do you guys have a quick command for getting a mask from initial model space to the final nlin?

This would be for the v1.x series as the v2 series does this automatically.

**Comment by mcvaneede** [comment]
The way that the mask from the initial model is propagated to the averages is not very intricate. The assumption is that the initial mask properly fits each of the subjects in your pipeline after the lsq6 alignment to the initial model. After each subsequent stage, an individual's mask is resampled with its "_lsq12.xfm", "_nlin-0.xfm", "_nlin-1.xfm"... transforms. The mask for the averages is created by running mincmath -max on all masks. So to create the mask for the final average you'd run something like this:

```
for {all_subjects} :
    mincresample -nearest_neighbour -transform {.../transforms/..._lsq12_and_nlin.xfm} ... initial_model_mask.mnc mask_for_subject.mnc

mincmath -max {all mask_for_subjects} final_avg_mask.mnc
```

**Comment by gdevenyi** [comment]
Thanks!

**Comment by bcdarwin** [comment]
Obsolete
