### ISSUE TITLE
weird repository/commit history issue

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#303]
Somehow when I pull from and push to develop the history gets weird and shows that I've committed whatever was in mice/develop, e.g.:

https://github.com/Mouse-Imaging-Centre/pydpiper/commit/6e091ec9717a2717c7da8ea7269ad274cd44a458

**Comment by gdevenyi** [comment]
Did your history get out of sync with the official by an amended commit or a rollback?

**Comment by bcdarwin** [comment]
It's possible.  I guess I'll destroy my local repo and clone again.
