### ISSUE TITLE
Best practices for pydpiper 2.0 runs?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#309]
With the changes to 2.0, I'm a bit unsure of the current best practice for running regular mouse brains through pydpiper.

My intentions:
- run MBM for deformations
- run MaGeT with DSUR_2016

Can you provide any insight as to the best practices for running 2.0? (registration protocols, command-line arguments, etc).

Thanks for your help!

**Comment by mcvaneede** [comment]
We might have jumped the gun a bit in terms of adding MAGeT in as default to the MBM pipelines. We're still using minctracc for the MAGeT registrations (we'll move to antsRegistration when we've done a parameter search), and pydpiper 2 doesn't automatically determine what step sizes and blurs to use for a non linear minctracc protocol. 

If you want to add MAGeT to an MBM pipeline you'll need something along these lines:

```
MBM.py \
...
--registration-method=mincANTS \
--lsq12-protocol=Pydpiper_testing_default_lsq12.csv \
...
--maget-registration-method=minctracc \
--maget-nlin-protocol=Pydpiper_minctracc_basic_MAGeT_protocol_mouse_brains.pl \
--maget-atlas-library=/path/to/DSUR_2016/
```

The lsq12 protocol for MAGeT will be the same as the one specified for MBM. I have:

```
"blur";0.28;0.19;0.14
"step";0.9;0.46;0.3
"gradient";FALSE;TRUE;FALSE
"simplex";2.8;1.4;0.9
"w_translations";0.4;0.4;0.4
```

This will generate atlases for all the lsq6 files in the pipeline. The content of the non linear protocol for MAGeT I'm using at the moment is:

```
"blur";0.25;0.25;0.25;0.25;0.25;0.1
"step";1.0;0.5;0.5;0.2;0.2;0.1
"iterations";60;60;60;10;10;10
"simplex";3.0;3.0;3.0;1.5;1.5;1.0
"gradient";FALSE;FALSE;TRUE;FALSE;TRUE;FALSE
"w_translations";0.4;0.4;0.4;0.4;0.4;0.4
"optimization";"-use_simplex";"-use_simplex";"-use_simplex";"-use_simplex";"-use_simplex";"-use_simplex"
"stiffness";0.98;0.98;0.98;0.98;0.98;0.98
"weight";0.8;0.8;0.8;0.8;0.8;0.8
"similarity";0.8;0.8;0.8;0.8;0.8;0.8
```
