### ISSUE TITLE
pydpiper/2.0.5 - Memory estimate too low for center estimation on 40um mouse scans

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#310]
I'm running into minctracc issues with:
```sh
Reading Volume: ...............................................................Cannot alloc 3D array of 504 by 630 by 504 elements of 8 bytes.
    Source position: /opt/quarantine/minc-toolkit/1.9.11/src/minc-toolkit-v2/libminc/volume_io/Volumes/multidim_arrays.c:357
```

I'm guessing that executors are not requesting enough memory on the cluster. I can override by setting a hard memory reuqest with --mem and --greedy and it then works.

**Comment by bcdarwin** [comment]
another option is to bump --default-job-mem to a higher value - since linear minctracc stages don't do any special estimates this will affect executors running minctracc without affecting *all* executors.

**Comment by gdevenyi** [comment]
Ah great, I didn't notice the addition of that. Thanks.

**Comment by mcvaneede** [comment]
yet another option is to set the --memory-factor We realized that the memory estimates worked on our local system, but that when we run things at the SickKids cluster, similar stages take more memory. The --memory-factor can be used to scale all memory estimates.

**Comment by gdevenyi** [comment]
Thanks @mcvaneede I'll start with the default-job-mem and see if that resolves it, if I run into issues with other stages I'll try the factor scaling.

**Comment by gdevenyi** [comment]
memory-factor is sufficient to solve this
