### ISSUE TITLE
pydpiper/2.0.5 final MAGeT voted labels not named or located properly

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#314]
Previously, voted labels ended up in <pipelinename>_processed/labels/<some subject info>.....votedlabels.mnc

in 2.0.5, instead, final voted labels are in <pipelinename>_processed/voted.mnc

**Comment by bcdarwin** [comment]
Fixed in 2.0.12.

**Comment by gdevenyi** [comment]
Closing my bugs before I get my test runs to work :)

**Comment by bcdarwin** [comment]
Reopened for you.  Anyway, the label files now get put in the output analysis.csv.

**Comment by gdevenyi** [comment]
Fixed
