### ISSUE TITLE
What to do about a couple bad LSQ6?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#324]
I'm doing a MBM with 257 brains and it looks like 3 or 4 "failed" at LSQ6.

Is there a suggested method to manually handle a couple failures in a very large run?

**Comment by bcdarwin** [comment]
In principle you could regenerate those _lsq6.mnc by hand using your own registration or whatever, though it's slightly tedious at the moment.  We plan to create an "add brains to pipeline" setting that wouldn't need to re-do LSQ12 and nonlinear parts in this situation, but that currently doesn't exist.  You could also just use ANTS to do affine/nonlinear alignment yourself, and rerun the stats part.


We definitely should think about how to increase configurability of individual pipeline runs...

________________________________

**Comment by gdevenyi** [comment]
Supplanted by #327
