### ISSUE TITLE
The use of masks with a commandline flag - missing?

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/pydpiper#326]
From the commandline, how to I inform MBM that I have masks for my files? I see this note in the news: "MBM and MAGeT can read files and masks from csv file containing `file` and optionally `mask_file` columns" but I see no option command-line wise for masks.

**Comment by bcdarwin** [comment]
You can't do it on the command line, but just create a 2-column csv with your filenames (and those column names) instead.

________________________________

**Comment by bcdarwin** [comment]
Closing for now -- let me know if there's some particular reason this is preferable to creating a csv.  (It seems just as difficult or more difficult to specify the masks on the command line unless you use two separate flags like --files f1.mnc f2.mnc --masks m1.mnc m2.mnc, but that will invariably lead to people masking the wrong files by accident.
