### ISSUE TITLE
Feature Idea: Allow xfm inputs for brains

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#327]
For badly-aligned brains it's sometimes easier to manually fix them.

It would be nice if pydpiper would accept xfm files if they exist rather than having to transform the brains before input.

**Comment by gdevenyi** [comment]
Alternatively, is -tfm_input_sampling handled properly on an input file?

**Comment by bcdarwin** [comment]
Yeah, this would be quite useful.  I've thought about adding it but it would require some care.

Pydpiper never touches sampling anywhere but it's possible this would work if it's respected by the tools in the pipeline ... I'm suspicious that some tools might be confused if your images don't have the same sampling, but hopefully this is corrected by resampling to the initial model early in the pipeline.  The registration chain currently checks that its inputs have the same sampling (not sure if this is currently needed) but the other pipelines don't.  Let me know if you try this and it works!  I'll try to add initial xfms soon.

**Comment by gdevenyi** [comment]
Followup: -tfm_input_sampling files seems to have been handled properly
