### ISSUE TITLE
"server too busy" Pyro error kills the executor

### ISSUE THREAD

**Issue by pipitone** [Mouse-Imaging-Centre/pydpiper#33]
I'm running my well-modified version of pydpiper (as of [aa91c06](https://github.com/pipitone/pydpiper/commit/aa81c067e2fb053fd64405147966ec03b48bb23d), say) on Scinet,  and running into a situation where executors die with the following output in the error log: 

```python
  File "../pydpiper/pydpiper/pipeline_executor.py", line 146, in launchPipeline
    runningMem -= runningChildren[j].get()[0]
  File "/scinet/gpc/tools/Python/Python272-shared/lib/python2.7/multiprocessing/pool.py", line 522, in get
    raise self._value
```

and the standard out log ends with:

```
Stage 24297 finished, return was: 0

server too busy
Shutting down executor.
```

I'm pretty sure this error isn't specific to my version of pydpiper... are you seeing this error ever?

The 'tubes tell me that "server too busy" from an `[ConnectionDeniedError] (http://packages.python.org/Pyro/10-errors.html)` thrown by Pyro.  The context in pipeline_executor.py for the lines shown in the error log above is the main loop in the executor in which is considering running a stage, and checking to see if it has enough resources to do so:

```python
 # Before running stage, check usable mem & procs
completedTasks = []
for j,val in enumerate(runningChildren):
    if val.ready():
        completedTasks.insert(0,j)
    for j in completedTasks:
        runningMem -= runningChildren[j].get()[0]
        runningProcs -= runningChildren[j].get()[1]
        del runningChildren[j]
```

I believe what is happening is that the although the child process completes, and returns true from `ready()`, it was not `successful()` due to the Pyro connect error.  When `.get()` is called, `AsyncResult` (from `multiprocessing.pool`) raises the Pyro exception. 

If I'm tracking this correctly, I have two suggestions. First, that the executor store the memory/processor allocation for each task, rather than expect to be able to get it back from the `AsyncResult` (i.e. `runningChildren` can be a map from `AsyncResult` instance to (memory, processors) allocated).  Second, if any Pyro call can potentially return a `ConnectionDeniedError` we should retry the call a few times rather than simply stop the executor.

**Comment by jasonlerch** [comment]
Fixed
