### ISSUE TITLE
Resolution: should we supersample?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#331]
Hi,

Just wondering if you guys have done any experiments on whether MBM builds should be supersampled or done in the native resolution of the scans.

**Comment by mcvaneede** [comment]
As far as I know we've never run any tests with supersampled data. One of the reasons being that already at the native resolution both computation time and memory usage are quite intense. 

A long time ago when we were still using ANIMAL as our main registration software and we used overnight scans at 30 micron resolution, we looked at the increased detection rate when adding a level of registration at 30 micron as opposed to only using a final 60 micron registration stage. We found that the increase in registration accuracy was only marginal at the cost of a lot of additional processing/memory.

Is there any evidence that supersampling is beneficial?

**Comment by gdevenyi** [comment]
There's some evidence for sampling into MNI space for CIVET that using a higher resolution template can give a bit more precision for cortex extraction.

**Comment by gdevenyi** [comment]
(i.e 0.5mm template instead of 1mm template)

**Comment by gdevenyi** [comment]
Just to follow up with a clarification, I mean the target common-space resolution.

If I don't tweak anything, that ends up being the resolution of the atlas, should I use that? The native resolution (via --resolution?) or something inbetween?

**Comment by mcvaneede** [comment]
I think for CIVET supersampling helps because you'll have more information to extract/build your surface. I don't know whether it makes much of a difference for volumetric analyses. 

Indeed, if you don't tweak anything, the registrations happen at the resolution of your model or target for the pipeline.

**Comment by gdevenyi** [comment]
Thanks.
