### ISSUE TITLE
pydpiper/2.0.6 MBM.py: --resolution doesn't work

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#333]
model is 0.02mm, set --resolution to 0.1mm (same as input scans)

resampled scans are 0.02mm resolution

**Comment by gdevenyi** [comment]
Any progress on this?

**Comment by bcdarwin** [comment]
I guess this would just resample the initial target(s) to the specified resolution?

Alternately we could allow using the resolution of the inputs instead of the model (although these might not all be the same ...).

@mcvaneede

**Comment by gdevenyi** [comment]
I think the intention was for resampling the initial target to the specified resolution.

As for option 2) this is slightly related to my "should we supersample?", one way to do this would be to set the resolution to that of the finest-resolution input.

Right now I keep around a pre-resampled initial target so that I don't end up running at 40um resolution.

**Comment by mcvaneede** [comment]
Definitely think that the easiest thing would be to use the resolution argument to resample the target or initial model to that resolution. That would allow you to specify the finest resolution of your input files. It should be easy to add a --use-finest-input-resolution flag or something along those lines.

**Comment by gdevenyi** [comment]
Still broken in 2.0.10

**Comment by nzxwang** [comment]
@bcdarwin if we use the method that you proposed: to edit the function registration_targets such that it returns the resolution-resampled initial target if --resolution is used, I run into two problems. Primarily, registration_targets would have to return a RegistrationTargets object if the --resolution flag is not used, and a Result object if it is used as it would have to resample the initial model. Secondarily, the registration_targets function currently does not get any information about where the pipeline is ran; where would the resampled inital model be output? Would it be tedious to add another argument to this function?

**Comment by bcdarwin** [comment]
Nick has fixed this.

**Comment by nzxwang** [comment]
i forgot about this.... i dont believe we included this in the NEWS or the release notes?

**Comment by bcdarwin** [comment]
I'll do it.
