### ISSUE TITLE
Feature Request: Change mincpik/montage outputs to jpg

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#335]
PNG is a format more suited for palette-based graphics than for photographic-like images, large numbers of subjects result in huge file sizes (50MB+)

A 95% quality JPEG is 10x smaller and pretty much indistinguishable in terms of quality

**Comment by bcdarwin** [comment]
fixed in develop

**Comment by nzxwang** [comment]
this got reverted by 9008dd8 because labels were no longer showing in the .jpg format
