### ISSUE TITLE
Incorrect transformation concatenation and stats in "pairwise nlin + build model"

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#339]
The Jacobian determinants are calculated using "avg-lsq12" and "final-nlin", where the "final-nlin" is the last transform calculated from the build-model part of the registration. However, the input file for this part of the registration is the output of the pairwise-nlin registrations. 

There are two options to fix this:
1) add the "avg-nlin" transformation as the second transformation in the concatenation above, or
2) use the lsq12 resampled file as the source for the final build model stage

I think I prefer the second option. Averaging the transformations in the pairwise nlin stage does not guarantee diffeomorphism, and we have this stage mainly to create a proper target for the non linear stages.

Similar considerations might hold for the tournament + build model approach for the non linear stage of the registration.

**Comment by mcvaneede** [comment]
Correction: it's not the "avg-nlin" that is omitted, but the first transformation from the build model stage. Meaning that the build model stage starts with the avg-lsq12 file, but resamples this file, and continues the model building with that file etc. This changes the issue a bit, but we probably want to start the model building from the "avg-lsq12" file at all times to minimize resampling artefacts during the registration procedure.

**Comment by bcdarwin** [comment]
Only affects develop; fixed in develop.
