### ISSUE TITLE
Documentation of protocol files?

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/pydpiper#341]
I'd like to start creating my own protocol files for some specific datasets but I'd like clear documentation on the variables and values for protocol files using minctracc, ANTs and linear minctracc. Are these somewhere? I cant seem to locate.

PS Not the default files but documentation on protocol files in general.

Thanks!

**Comment by psteadman** [comment]
When using ANTS I dont see the blur portion of the protocol file being used. Makes me think its not necessary.

Here is my protocol file:
``` 
blur";-1,0.02;-1,0.01;-1,0.008
"gradient";False,True;False,True;False,True
"similarity_metric";"CC,CC";"CC,CC";"CC,CC"
"weight";"1,1";"1,1";"1,1"
"radius_or_histo";"5,5";"3,3";"3,3"
"transformation";"SyN[0.3]";"SyN[0.3]";"SyN[0.1]"
"regularization";"Gauss[2,1]";"Gauss[2,1]";"Gauss[2,1]"
"iterations";"500x200x100x0";"100x100x100x40";"100x100x100x150"
"useMask";False;True;True
```
Here are the first stages of the nlin portion:
```
0       mincblur -clobber -no_apodize -fwhm 0.006 file1.mnc file1_fwhm0.006 -gradient
1       mincblur -clobber -no_apodize -fwhm 0.006 file2.mnc file2_fwhm0.006 -gradient
2       ANTS 3 --number-of-affine-iterations 0 -m 'CC[file1.mnc,file2.mnc,1.0,5]' -m 'CC[file1_fwhm0.006_dxyz.mnc,file2_fwhm0.006_dxyz.mnc,1.0,5]' -t SyN[0.3] -r Gauss[2,1] -i 500x200x100x0 -o NLIN_ANTS_nlin-0.xfm
```

**Comment by bcdarwin** [comment]
It's not being used in the current release but we realized that was a mistake so it'll be supported again in the next release.

**Comment by psteadman** [comment]
Yea I see the line in registration.py 
https://github.com/Mouse-Imaging-Centre/pydpiper/blob/master/pydpiper/minc/registration.py#L1527

Okay thanks Ben!

**Comment by bcdarwin** [comment]
No, develop is far ahead of master at the moment.  I need to release but first I need to test and clean up a few things (e.g., antsRegistration has been added but I didn't write a protocol parser for it yet ...)

**Comment by bcdarwin** [comment]
Master should always be in sync with the most recent release (2.0.9 presently).

**Comment by psteadman** [comment]
Okay I figured that was your approach I just wasnt sure. Happy to know antsRegistration is in there as I was thinking of testing the script by converting to nifti, but if its been worked in thats great. Any timeline? I might pull your dev branch then and do some play from there.

**Comment by psteadman** [comment]
Okay I am going to take a stab at a wiki page on the protocol files and then perhaps you can review/edit (thus I will close this comment)

**Comment by bcdarwin** [comment]
Thanks!  It's a bit unfortunate that the documentation can't be generated automatically as argparse does but that's in the 'future work' category ...

**Comment by bcdarwin** [comment]
Support for explicitly specifiying the blurring fwhm is restored in develop as of 9460766, but you generally don't need to specify it.

I recall that @mcvaneede also wanted this feature at some point in the distant past :)
