### ISSUE TITLE
Better Singularity integration?

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#377]
Hopefully one will soon be able to build or download Singularity containers containing Pydpiper (see https://github.com/vfonov/minc-toolkit-containers/pull/2/files).

Currently one can run have Pydpiper run executors from within a container (this using the sandboxed registration tools) via `--executor_wrapper='singularity exec --bind /shared/fs/containing/files /path/to/singularity/containers'`.  Similarly one can run the main Pydpiper process from (the same) container in the obvious way.  [Less conveniently, one ought to be able to containerize individual stages via --cmd-wrapper (note inconsistent hyphenation...) but this currently doesn't work with multi-token wrappers due to a string processing bug.]

Overall the situation is flexible (modulo bug) but a little tedious and stringy.

**Comment by bcdarwin** [comment]
So some experiments reveal it's not actually too easy to do Slurm cluster submission from within a Singularity container.  Unsure about SGE or Torque since I don't have a system that runs both one of these and Singularity.

For Slurm, the problem is making the Slurm (and Munge) infrastructure available from within the container.  For some work in this direction, see [this thread](https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/syLcsIWWzdo).  However, a couple problems remain: (i) it seems like the UIDs of the Slurm/Munge users needs to be known at container creation time, making it impossible to provide prebuilt containers; (ii) mounting /var/run/munge using --bind or SINGULARITY_BINDPATHS=... seems to fail silently for some reason.

The obvious solution is to submit from outside a container, e.g., by decoupling the pipeline planning and submission logic in some way.  For instance, the containerised server could provide information about runnable stages, and a separate process (not containerised but also not containing 'scientific' logic) could then determine jobs to submit.

**Comment by gdevenyi** [comment]
I had done this bit of work to containerize my antsRegistration-MAGeT pipeline:
https://github.com/pipitone/qbatch/commits/container
https://github.com/cobralab/antsRegistration-MAGet/tree/container

It kinda passes the job submission command out of the pipeline container to launch a new container job elsewhere

**Comment by bcdarwin** [comment]
We have this as of 2.0.18 with the --use-singularity and --container-... flags.  Pydpiper itself doesn't offer any special workarounds for the Slurm submission issues but you can generate a Makeflow file and use the Makeflow backend without having Pydpiper installed on your cluster at all.
