### ISSUE TITLE
use Vlad's Scipy-based xfmavg

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#385]
... better numerical properties and gets rid of the annoying octave dependency (which is missing in Vlad's singularity containers).

I think this is still Python2-based unfortunately so it might be hard to support all users out of the box despite @nzxwang's work on running stages inside modified environments.

**Comment by bcdarwin** [comment]
Haven't tried.  Note that Pydpiper also needs to average nonlinear transforms when run with '--registration-strategy=pairwise' or `...=pairwise_and_build_model`.

**Comment by gdevenyi** [comment]
Ah, in the case of ANTs, affines and nonlinear are always separated, so they use AverageImages to just average deformation fields.

**Comment by bcdarwin** [comment]
That would work for us too in this particular instance.

**Comment by gdevenyi** [comment]
Options :+1:
