### ISSUE TITLE
Newer minc-toolkit versions have a -labels option

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#398]
minc-toolkit added a ``-labels`` option for most of the programs where intensities could be renormalized/modified:

```
 -labels:                   integer operation on labels
```

I believe its a "strong" version of -keep_real_range as it also disables the scaling features.

**Comment by gdevenyi** [comment]
https://github.com/BIC-MNI/minc-tools/blob/develop/progs/mincresample/mincresample.c#L1642-L1648

**Comment by bcdarwin** [comment]
Fixed in develop.
