### ISSUE TITLE
Please don't forcepush and/or delete/re-release versions :(

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#406]
Github doesn't show a notification when you do this.

Also, my install of v2.0.12 is no longer v2.0.12

**Comment by gdevenyi** [comment]
Second instance :(

https://github.com/Mouse-Imaging-Centre/minc-stuffs/commit/ca50847fded5416cd2d06377301667b7829f43e4#comments

**Comment by bcdarwin** [comment]
You're right ... I didn't force push code but adjusted the tag.  When I was doing it I felt it was justified since I fixed a couple serious bugs that made v2.0.12 difficult to use but I won't do it again.
