### ISSUE TITLE
problems with CSV file merging

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#413]
Depending on combinations of pipeline (MBM vs two-level), --{no-,}run-maget setting, --files/--csv-file, etc., various crashes are possible (see also #382 for more issues).  Overall the problem seems to be due to conditionally present _columns_ in data frames.  I propose the following fixes:

- get_imgs be generalized to handle both cases by returning additional CSV columns so that (1) group IDs are available to the two-level pipeline and other input metadata (including file, group) is available to be written out to 'analysis.csv'.
- get_imgs defaults to filenames relative to the CSV file but can optionally handle filenames relative to the pipeline (via a flag).  Open to adopting the opposite convention.
- the additional _merge columns be removed from the code since they both cause breakage (as they are only conditionally present!) and potentially wrong (is the basename really always sufficient to identify a file???) and actual paths be used instead.

**Comment by gdevenyi** [comment]
Just bitten by this for a --bootstrap with no maget or masking. Will test.

**Comment by gdevenyi** [comment]
develop seems to work, had to figure out how to install xfmavg_scipy.py :)

**Comment by bcdarwin** [comment]
I have a PR to fix the installation ....

________________________________

**Comment by gdevenyi** [comment]
ah, interesting, I was installing pyezminc rather than minc2-simple, both seem to have xfmavg_scipy.py
