### ISSUE TITLE
Better handling of unfinished stages when executors die

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#42]
This issue handles the case when an executor dies because it is running on a queueing system and the job exceeds the wall clock time, thus killing the executor. 

The code needs to be re-written so that when an executor dies, the following happens:
1. The server keeps track of its executors, so knows when the executor dies. 
2. The server knows which stages the executor was running, so if they are unfinished, they can be put back into the queue. 

Currently, the only way to handle this situation is to restart the server and use the --restart option. If the server stays running after the executor dies, it has no knowledge of what happened to those stages. 

Jon will be tackling this issue first as he is currently running into it quite frequently on scinet.

**Comment by jasonlerch** [comment]
Done
