### ISSUE TITLE
Error running test: The 'pydpiper==2.0.13' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by Omroth** [Mouse-Imaging-Centre/pydpiper#432]
Hey, just trying to run the test and I get this error.  Is this a path issue?

"The 'pydpiper==2.0.13' distribution was not found and is required by the application"

(I've run setup.py install)

**Comment by gdevenyi** [comment]
As with other issues you have reported, please provide *full* details of exactly how you prepared the system beforehand as well as all of your input and all of your outputs.

If you examine the setup.py install, I suspect you didn't install successfully.

**Comment by Omroth** [comment]
Thank you Gabriel I will do that.

**Comment by Omroth** [comment]
Ok.

Pydpiper was downloaded with

git clone https://github.com/Mouse-Imaging-Centre/pydpiper.git

I am attempting to install and run it in a container based on 

nistmni/minc-toolkit:1.9.16

I successfully install minc-stuffs.

Attached (file) is the output of

python3 setup.py install

And 

pydpiper_testing/test_MBM_and_MAGeT.py test-data/

fails with

pkg_resources.DistributionNotFound: The 'pydpiper==2.0.13' distribution was not found and is required by the application

[pydpiper_setup_log.txt](https://github.com/Mouse-Imaging-Centre/pydpiper/files/3519732/pydpiper_setup_log.txt)

The only potential problem I could imagine is that setup.py is being run with python 3.5.2 rather than 3.6 (thus the f-string errors) - I'm running it like that because of an issue getting python-dev working with both 3.5.2 and 3.6 at the same time.  However it does look like the install is succeeding.

**Comment by gdevenyi** [comment]
That error is pretty clear, the egg files for pydpiper didn't get installed because of the syntax error, as such the pydpiper scripts installed in bin can't launch the egg libraries. You'll need 3.6 to support f-strings.

**Comment by gdevenyi** [comment]
This is a bug since the fstring was introduced but setup.y currently only requires 3.5.

Either we'll fix the fstring or upgrade the requirements.

**Comment by Omroth** [comment]
Thank you.
