### ISSUE TITLE
pydpiper setup.py specifies >3.5 however since f-strings are used we need 3.6

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#433]
https://github.com/Mouse-Imaging-Centre/pydpiper/blob/master/setup.py#L8

https://github.com/Mouse-Imaging-Centre/pydpiper/blob/2c2e390776f1b933832ce874d49d26e756534eb1/pydpiper/core/arguments.py#L115

See #432 for an install failure triggered by this.

**Comment by gdevenyi** [comment]
https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals

**Comment by nzxwang** [comment]
This was fixed by d80bb9b993f0a7994a0c54b62ea0cbe3ee8b9ce9
