### ISSUE TITLE
Is it possible to run test_MBM_and_MAGeT without using qbatch?

### ISSUE THREAD

**Issue by Omroth** [Mouse-Imaging-Centre/pydpiper#434]

**Comment by gdevenyi** [comment]
https://github.com/Mouse-Imaging-Centre/pydpiper/blob/master/pydpiper_testing/test_MBM_and_MAGeT.py#L6

sample.cfg chooses how the pipeline is run.

**Comment by gdevenyi** [comment]
Also note: https://github.com/Mouse-Imaging-Centre/pydpiper/issues/424
