### ISSUE TITLE
Is asymmetry.py functional?

### ISSUE THREAD

**Issue by Dorky-Lever** [Mouse-Imaging-Centre/pydpiper#436]
Hi everyone, 

Is assymetry.py functional or is it under development? 

Kind Regards, 
Kyle Drover

**Comment by bcdarwin** [comment]
I haven't used it in a while but it seems to be working.  It's just a thin layer over twolevel_model_building.py which flips each image so it may be affected by a couple recent bugs affecting that pipeline such as #426 and #440.

**Comment by bcdarwin** [comment]
Closing for now; feel free to re-open if you encounter any issues.
