### ISSUE TITLE
MBM and Maget test - executors don't register with server

### ISSUE THREAD

**Issue by Omroth** [Mouse-Imaging-Centre/pydpiper#437]
Running:

pydpiper_testing/test_MBM_and_MAGeT.py test-data/

and has been waiting for an hour at this stage, which I presume is wrong:

Warning: Not masking your images from atlas masks after LSQ6 alignment ... probably not what you want (this can have negative effects on your registration and statistics) [/usr/local/lib/python3.6/dist-packages/pydpiper-2.0.13-py3.6.egg/EGG-INFO/scripts/MBM.py:315]

Total number of stages in the pipeline:  1858
Number of stages already processed:      0
Daemon is running at: 172.17.0.3:39423
The pipeline's uri is: PYRO:obj_2a7e1beb261d4c34a2fb47b949b311a2@172.17.0.3:39423
.0.localhost

Submitted 20 executors (clients) to the queue.
Waiting for them to register with the server...
.........................................................................................................................................................................................................................................................................................

Any suggestions as to what might be the issue?

--

Pydpiper was downloaded with

git clone https://github.com/Mouse-Imaging-Centre/pydpiper.git

It is run on a container based on:

nistmni/minc-toolkit:1.9.16

torque was built and installed from github latest.

**Comment by gdevenyi** [comment]
Containers cannot communicate outside the cluster. If you want to do cluster work, you will need to install pydpiper in the base system.

**Comment by gdevenyi** [comment]
If you wish to run locally you can do so by editing the sample.cfg, as per:
https://github.com/Mouse-Imaging-Centre/pydpiper/blob/master/pydpiper_testing/test_MBM_and_MAGeT.py#L6

**Comment by Omroth** [comment]
Could you just be a bit more explicit of what exactly to change to run locally?  I've been through every line of that file and none seem appropriate.  I tried setting num_execs to 0 and 1 just in case that was taken into consideration elsewhere, but it was not.

**Comment by gdevenyi** [comment]
The configuration file is a 1-1 mapping to ``--help`` options:
```
  --local               Don't submit anything to any specified queueing system
                        but instead run as a server/executor

```

**Comment by Omroth** [comment]
Thank you.

**Comment by Omroth** [comment]
Hi, sorry - I'm still having trouble with this.  After running with the "local" option I get the following:

`Total number of stages in the pipeline:  1858
Number of stages already processed:      0
Daemon is running at: 172.17.0.5:45343
The pipeline's uri is: PYRO:obj_e25c6374de0f4b98b47a4efb6f016015@172.17.0.5:45343
.
Submitted 20 executors (clients) to the queue.
Waiting for them to register with the server...

Client registered (Eh!): PYRO:obj_b4166e290fe54fc6b1da884756df5088@172.17.0.5:37335
Client registered (Eh!): PYRO:obj_016fab94f6ad4714ab7baad9f228018a@172.17.0.5:40189
Client registered (Eh!): PYRO:obj_cd57c767ba6345d5b20304cfce9a1cd8@172.17.0.5:39919
Client registered (Eh!): PYRO:obj_06da3e3683d244f5901c38bd8dfe3a90@172.17.0.5:41167
Client registered (Eh!): PYRO:obj_2e79b935840c4dd9aab18d1437938a43@172.17.0.5:35385
Client registered (Eh!): PYRO:obj_ef6e82df4f38438e9cfd348394bb67fc@172.17.0.5:45387
Client registered (Eh!): PYRO:obj_ef57c2d3e800494186ba75e0fd09f534@172.17.0.5:41887
Client registered (Eh!): PYRO:obj_4828b335c0434fd4b4ed5be9dd02e3d3@172.17.0.5:43061
Client registered (Eh!): PYRO:obj_adf01ed35dcd4bb98059203366d4691f@172.17.0.5:42801
Client registered (Eh!): PYRO:obj_16a5caf850b847edbd4b22140b0d3b45@172.17.0.5:43197
Client registered (Eh!): PYRO:obj_7243652fd26b42769f81e4629587025f@172.17.0.5:33261
Client registered (Eh!): PYRO:obj_b6bddfdb32c544a4986351ee6fbb9410@172.17.0.5:36257
Client registered (Eh!): PYRO:obj_eadc3d74627d40678097b868f5b1cef7@172.17.0.5:37051
Client registered (Eh!): PYRO:obj_a5c96edfe67f4c8b9bea87257c5e728c@172.17.0.5:46655
Client registered (Eh!): PYRO:obj_98eddcd99a5f4c1388ab2dc39d72a67a@172.17.0.5:35869
Client registered (Eh!): PYRO:obj_0ae1e159dd004bcaa8cdbc68e1182e63@172.17.0.5:33371
Client registered (Eh!): PYRO:obj_0a94ed3c2ad04eff96ed0b943ff5597e@172.17.0.5:40705
Client registered (Eh!): PYRO:obj_69845758feb34cefbe617adbd84e8edf@172.17.0.5:41949
Client registered (Eh!): PYRO:obj_fe7551b1cacf4e06b5c3b2c09986b795@172.17.0.5:45435
Client registered (Eh!): PYRO:obj_1f4d4c6e475646c8a486f49a5003a1b1@172.17.0.5:45999.......`

And then this waits forever.  I'm sure this is just because of my lack of knowledge of Torque/Grid Engine, but just pointing me to what I'm doing wrong would be really appreciated.

**Comment by Omroth** [comment]
Sorry to repoen this - I just want to check that after:

`Total number of stages in the pipeline:  1858
Number of stages already processed:      0
Daemon is running at: 172.17.0.5:45343
The pipeline's uri is: PYRO:obj_e25c6374de0f4b98b47a4efb6f016015@172.17.0.5:45343
.
Submitted 20 executors (clients) to the queue.
Waiting for them to register with the server...

Client registered (Eh!): PYRO:obj_b4166e290fe54fc6b1da884756df5088@172.17.0.5:37335
Client registered (Eh!): PYRO:obj_016fab94f6ad4714ab7baad9f228018a@172.17.0.5:40189
Client registered (Eh!): PYRO:obj_cd57c767ba6345d5b20304cfce9a1cd8@172.17.0.5:39919
Client registered (Eh!): PYRO:obj_06da3e3683d244f5901c38bd8dfe3a90@172.17.0.5:41167
Client registered (Eh!): PYRO:obj_2e79b935840c4dd9aab18d1437938a43@172.17.0.5:35385
Client registered (Eh!): PYRO:obj_ef6e82df4f38438e9cfd348394bb67fc@172.17.0.5:45387
Client registered (Eh!): PYRO:obj_ef57c2d3e800494186ba75e0fd09f534@172.17.0.5:41887
Client registered (Eh!): PYRO:obj_4828b335c0434fd4b4ed5be9dd02e3d3@172.17.0.5:43061
Client registered (Eh!): PYRO:obj_adf01ed35dcd4bb98059203366d4691f@172.17.0.5:42801
Client registered (Eh!): PYRO:obj_16a5caf850b847edbd4b22140b0d3b45@172.17.0.5:43197
Client registered (Eh!): PYRO:obj_7243652fd26b42769f81e4629587025f@172.17.0.5:33261
Client registered (Eh!): PYRO:obj_b6bddfdb32c544a4986351ee6fbb9410@172.17.0.5:36257
Client registered (Eh!): PYRO:obj_eadc3d74627d40678097b868f5b1cef7@172.17.0.5:37051
Client registered (Eh!): PYRO:obj_a5c96edfe67f4c8b9bea87257c5e728c@172.17.0.5:46655
Client registered (Eh!): PYRO:obj_98eddcd99a5f4c1388ab2dc39d72a67a@172.17.0.5:35869
Client registered (Eh!): PYRO:obj_0ae1e159dd004bcaa8cdbc68e1182e63@172.17.0.5:33371
Client registered (Eh!): PYRO:obj_0a94ed3c2ad04eff96ed0b943ff5597e@172.17.0.5:40705
Client registered (Eh!): PYRO:obj_69845758feb34cefbe617adbd84e8edf@172.17.0.5:41949
Client registered (Eh!): PYRO:obj_fe7551b1cacf4e06b5c3b2c09986b795@172.17.0.5:45435
Client registered (Eh!): PYRO:obj_1f4d4c6e475646c8a486f49a5003a1b1@172.17.0.5:45999.......`

I should expect no further output until the process is finished, in approx 24 hours?

**Comment by gdevenyi** [comment]
You can follow progress at pipeline.log

The server itself doesn't output much of anything while its running except for submitting new executors and reporting they registered.

**Comment by Omroth** [comment]
Thanks Gabriel.
