### ISSUE TITLE
Manually overriding stages within a pipeline? 

### ISSUE THREAD

**Issue by Dorky-Lever** [Mouse-Imaging-Centre/pydpiper#449]
Hi Everyone, 

In to relation to https://github.com/Mouse-Imaging-Centre/pydpiper/issues/448; Is it possible to manually correct stages after a pipeline is initialised?

Kind Regards,
Kyle Drover

**Comment by bcdarwin** [comment]
In principle you could write some bash/Python/... script that given a command prints out a fixed version of that command and then install it in Pydpiper with `--cmd-wrapper /path/to/script.py` but I've never actually tried this.  Some more convenient builtin functionality would be nice to have, certainly, but it'd still probably operate at the level of the whole pipeline like this?

**Comment by Dorky-Lever** [comment]
I think I have a fix but I need to test it fully. I'll make a pull request if it works.
