### ISSUE TITLE
setLastXfm vs addAndSetXfmToUse

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#46]
Need some sort of guideline about when to use one vs. the other. 

addAndSetXfmToUse adds transforms to a dictionary and sets the last xfm to use between two files. This is defined in the RegistrationPipeFH class.  

setLastXfm only sets self.lastTransform in the RegistrationGroupedFiles class, but does not update the self.transforms hash. 

Usually addAndSetXfmToUse is preferred, but there are instances when only setLastXfm is needed. Need to either document this or remove setLastXfm.

**Comment by jasonlerch** [comment]
will be dealt with #179
