### ISSUE TITLE
small error with is_effectively_complete

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#47]
When the pipelineDaemon is run, it calls the function skip_completed_stages, which in turn calls is_effectively_complete. This function checks to see if all output and inputs exist for a specific stage, and if so, it assumes the stage is complete and does not run it. (This happens if running the pipeline with or without the --restart function.) 

If either of the inputs or outputs exist, but have errors and/or are not "fully written", the stages will be marked as complete, even though they aren't. Example: pipeline dies or is killed in the middle of writing a minc file. The minc file will therefore exist and pass the aforementioned checking, but will cause all subsequent stages to crash, as it has not been fully written.

We need to work around this error. Possible solution:
1. in is_effectively_complete:
if all_files_exist:
   if pydpiper-backups dir exists from previous run:
       is stage finished:
         if no: 
            all_files_exist = False
   else (ie no backups dir):
       print warning to log file

This won't solve the problem in all cases (for example, if there is no backups directory) but it will at least provide more error checking.

**Comment by jasonlerch** [comment]
now handled stage hashes
