### ISSUE TITLE
Fix bugs with --pbs queueing option

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#50]
1. Currently, when --num-executors=1 is specified with --procs=56 (for example), even with the script constructed so that it automatically asks for 7 nodes (with 8ppn), all processed appear to be put on one node. 

2. Review scinet documentation for serial jobs. May want to have the code log into nodes and submit jobs to launch execs after server is running.

**Comment by jasonlerch** [comment]
Fixed.
