### ISSUE TITLE
General Issue: MASKING

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#60]
Bucket issue (for now) to place masking related notes/concerns/designs. We can close/split into separate issues later as needed. 

Currently masking is handled (as it likely should be) in the initializeInputFiles function in registration_functions.py. There is also a maskFiles function in MAGeT_modules.py

Current options in initializeInputFiles: 
1. If no mask directory is specified, do not use a mask
2. If a mask directory is specified, there can be one mask for all brains, or an individual mask for each brain. If the latter is chosen, names must match the names of input files. 

I think this convention is fine...may want to make this a separate function?

maskFIles multiplies inputs by masks (specifically created using MAGeT) to create a new masked lastBasevol. This may want to be moved out of MAGeT_modules and put someplace more general, as I could see this being used in multiple places. 

Additional Notes:
1. Masking is also needed for non-uniformity correction. This module/set of modules has not yet been written. 
2. Any resampling of files will need to include resampling of associated masks, so we'll need to keep this in mind.

**Comment by bcdarwin** [comment]
This mostly deals with the old codebase.
