### ISSUE TITLE
Default resampling should be -sinc

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#63]
When running build model, default resampling should be -sinc, and this should be added to the mincresample atoms where appropriate. (e.g. Not necessarily when resampling labels in MAGeT)

Note: Currently, the default in the non-linear mincANTS registration in the current build model is -tricubic.

**Comment by bcdarwin** [comment]
MBM with mincANTS currently generates commands to resample with -sinc for nonlinear transformations, though this is set in NLIN.py rather than the mincresample atom.
