### ISSUE TITLE
Consistency in module importing

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#64]
Currently, module importing is not done consistently. My fault. 

For example, in some files, we might have:

import pydpiper_apps.minc_tools.minc_modules as mm

whereas in others, specific functions or classes are imported:

from pydpiper_apps.minc_tools.minc_atoms import mincresample, mincresampleMask, mincANTS

I'm not sure the best way to do this or whether it should be different on a case by case basis, but ultimately whatever is decided we should be consistent.

**Comment by bcdarwin** [comment]
I think we're mostly importing specific names at this point.  Also, I don't think this is too important as long as we're not importing `*`.
