### ISSUE TITLE
Third, intermediate file handling class needed?

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#68]
See for example NLIN.py:

We are currently using the RegistrationPipeFH class for the nlin-1/2/3.mnc files, because we need to blur them, and this is not handled in the base class. However, we don't need all of the subdirectories and naming that this creates. 

I think a third (and possible more than three) file handling class is needed, to handle intermediate cases like this. This might, of course, mean that some tweaking of the existing classes and what they do is needed.

**Comment by jasonlerch** [comment]
related to #179
