### ISSUE TITLE
need to assure that mincAtoms, etc., can work with filenames (and not only filehandlers)

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#69]
At the moment the function checkArrayLengths (and the blurring of the input files) is only executed when the input files are provided through file handlers. This should also be done for string input arguments, so probably should be run outside of the try-except block?

**Comment by jasonlerch** [comment]
after rewrite (see #179 ), need to think about whether we want to maintain this functionality

**Comment by bcdarwin** [comment]
This issue no longer makes sense in the context of Pydpiper>=2.0.
