### ISSUE TITLE
Masking to aid MINC compression?

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#72]
There is a way to turn on internal compression for MINC files, which can greatly reduce the size of the files. According to a thread on the MINC-development list, a good/safe setting is:

MINC_COMPRESS=4

(http://www.bic.mni.mcgill.ca/pipermail/minc-development/2011-August/000932.html)

The compression scheme works best on masks/segmentations. On regular MRI scans, compression does not give you a lot of saved disk space. One way to improve disk space usage, would be to roughly mask files (for instance during a registration pipeline) in order to effectively compress the background.

**Comment by jasonlerch** [comment]
Buy more hard-drive space ... probably not worth worrying about.
