### ISSUE TITLE
what is/should be the default error handling by getBlur()

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#74]
When getBlur() is called for a file handler, and the requested fwhm has not already been applied to the input file, the assignments in:

https://github.com/mfriedel/pydpiper/blob/master/pydpiper_apps/minc_tools/registration_file_handling.py#L35-L38

try to access a key in the blurs or gradients dictionaries that does not exist. Do we want to produce a better sort of error handling here? Ideally we would create the blur file if it doesn't exist? I don't think that's really possible at the moment, but would it be a good idea to improve the current behaviour towards the request of a non existent blur file.

**Comment by jasonlerch** [comment]
will go away with #179
