### ISSUE TITLE
Assigning memory for minctracc and mincANTS calls

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#78]
Currently, in order to override default minctracc and mincANTS variables, a csv file can be inputted for either that specifies things like step size, number of iterations, etc. 

What was not included in this file (somewhat deliberately) was the ability to specify the amount of memory for each stage. This is because memory is handled elsewhere in the code. 

However, we might want to rethink this, since the default amount of memory specified for each stage is 2GB, and we often need much more than that for later nlin generations, particularly mincANTS.

**Comment by bcdarwin** [comment]
Done for mincANTS in c1782fee and 2442f52c.  (Not quite: any stage of form ...x0x0 gets the estimate for ...x0)
