### ISSUE TITLE
Subject matter should be a single parameter

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#88]
LSQ6 and LSQ12 now have an option to specify the subject matter (e.g. mouse brain, mouse embryo, human brain), which will automatically set registration parameters. This is necessary since setting registration parameters based on resolution will not be effective if the resolution is too large. This was introduced by Matthijs in commit 3b2ce3a37d608d73. 

--subject-matter should be a single parameter that is specified once for the whole registration rather than separately for each module.

**Comment by jasonlerch** [comment]
related to #158
