### ISSUE TITLE
Command line option to specify resolution for file registration

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#89]
This option will function similarly to -downsampling-factor in the old MBM. 

Example usage: input files are 20 microns.
You want to register everything at 60 microns. 
You specify a resolution of 60 microns on the command line. 

Files are resampled once, using the SetResolution function, and then registered at the new resolution going forward. 

If an init-model is specified at the original resolution, it will need to be resampled to this new resolution prior to an LSQ6 registration.

**Comment by bcdarwin** [comment]
You can use `--resolution` for this, but you won't get resampling back to your input resolution.
