### ISSUE TITLE
LSQ12 maxpairs should be implemented

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#93]
Although there is currently a command line option for LSQ12 max pairs, the functionality is not implemented. The default is set to None, so that all pairs are registered. 

This functionality is necessary so that for large registrations, only a subset of all possible pairs are registered to get an average LSQ12 transform for each brain. This subset should be randomly chosen, as it is in the old version of build model.

**Comment by jasonlerch** [comment]
Done by Ben.
